{
 * UConfig.pas
 *
 * Implements class that stores program's configuration information.
 *
 * v1.0 of 10 Mar 2007 -  Original version.
 * v1.1 of 29 May 2009 -  Added support for doc type that generates a complete
 *                        XHTML document but which hides embedded CSS from
 *                        browser in HTML comments.
 *
 *
 * ***** BEGIN LICENSE BLOCK *****
 *
 * Version: MPL 1.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with the
 * License. You may obtain a copy of the License at http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
 * the specific language governing rights and limitations under the License.
 *
 * The Original Code is UConfig.pas.
 *
 * The Initial Developer of the Original Code is Peter Johnson
 * (http://www.delphidabbler.com/).
 *
 * Portions created by the Initial Developer are Copyright (C) 2007-2009 Peter
 * Johnson. All Rights Reserved.
 *
 * ***** END LICENSE BLOCK *****
}


unit UConfig;


interface


type

  {
  TInputSource:
    Enumerates different sources of input used by program.
  }
  TInputSource = (
    isStdIn,        // standard input
    isClipboard     // clipboard
  );

  {
  TOutputSink:
    Enumerates different output sinks used by program
  }
  TOutputSink = (
    osStdOut,       // standard output
    osClipboard     // clipboard
  );

  {
  TDocType:
    Enumerates various kinds of documents that can be generated by program.
  }
  TDocType = (
    dtXHTML,        // complete XHTML document
    dtXHTMLHideCSS, // complete XHTML document with CSS hidden in comments
    dtXHTMLFragment // a fragment of HTML code, with no embedded style sheet
  );

  {
  TConfig:
    Class that records details of program's configuration. Used to determine
    how program behaves.
  }
  TConfig = class(TObject)
  private
    fQuiet: Boolean;              // Value of Quiet property
    fDocType: TDocType;           // Value of DocType property
    fInputSource: TInputSource;   // Value of InputSource property
    fOutputSink: TOutputSink;     // Value of OutputSink property
    fShowHelp: Boolean;           // Values of ShowHelp property
  public
    constructor Create;
      {Class constructor. Initialises object's default property values.
      }
    property InputSource: TInputSource
      read fInputSource write fInputSource default isStdIn;
      {Describes source to be used for program's input}
    property OutputSink: TOutputSink
      read fOutputSink write fOutputSink default osStdOut;
      {Describes destination of program's output}
    property DocType: TDocType
      read fDocType write fDocType default dtXHTML;
      {Type of document to be generated}
    property Quiet: Boolean
      read fQuiet write fQuiet default False;
      {Whether program is to display project progress on console. Setting Quiet
      to true inhibits visual output}
    property ShowHelp: Boolean
      read fShowHelp write fShowHelp default False;
      {Whether program is to display help}
  end;


implementation


{ TConfig }

constructor TConfig.Create;
  {Class constructor. Initialises object's default property values.
  }
begin
  inherited;
  fInputSource := isStdIn;
  fOutputSink := osStdOut;
  fDocType := dtXHTML;
  fQuiet := False;
  fShowHelp := False;
end;

end.

